require_relative 'game'
require_relative 'player'
require_relative 'board'
require_relative 'evaluation'
require_relative 'piece'
require_relative 'coordinate'
require_relative 'fen'
require_relative 'rook'
require_relative 'knight'
require_relative 'bishop'
require_relative 'queen'
require_relative 'king'
require_relative 'pawn'
require_relative 'kingside_castle'
require_relative 'queenside_castle'
require_relative 'board_to_fen'

Game.new.play_game
